### ISSUE TITLE
getmezzio.org returns "Unknown host"

### ISSUE THREAD

**Issue by froschdesign** [mezzio/mezzio.dev#1]
### Bug Report

https://getmezzio.org returns "Unknown host".

We should redirect getmezzio.org and mezzio.dev to docs.mezzio.dev until the website is finished.

---

Related forum post: https://discourse.laminas.dev/t/cant-get-to-getmezzio-org/1434/2

**Comment by weierophinney** [comment]
Where are you seeing the link for getmezzio.org, exactly?

**Comment by froschdesign** [comment]
I've asked myself the same question.

https://github.com/search?q=org%3Alaminas+getmezzio.org&type=Code
https://github.com/search?q=org%3Amezzio+getmezzio.org&type=Code

**Comment by weierophinney** [comment]
Okay, so:

- I'll setup DNS to redirect to docs.mezzio.dev
- We should update those various locations to point to docs.mezzio.dev

**Comment by weierophinney** [comment]
I updated laminas.github.io when merging my FAQ on migrating zendframework/zendframework.

**Comment by weierophinney** [comment]
getmezzio.org DNS is setup at this time to forward to docs.mezzio.dev. However, SSL forwarding could take up to 24 hours. (I've verified that http://getmezzio.org forwards correctly at this time, however.)

**Comment by weierophinney** [comment]
All references across all repos in all organizations are now updated.
